### ISSUE TITLE
关于联合训练器

### ISSUE THREAD

**Issue by lpdbz** [Sapphire-star/PFCR#2]
请问代码联合训练器部分，这个四个训练器的区别是什么？分别起什么作用啊？
> 查看了代码，感觉代码几乎差不多呀，可能是我没有看懂，恕我冒昧，问的问题可能有点不太专业
<img width="113" alt="联合训练器" src="https://github.com/Ckano/PFCR/assets/90132046/32452256-8994-45e8-b5d0-f59a85496502">

**Comment by Ckano** [comment]
> lpdbz



> 请问代码联合训练器部分，这个四个训练器的区别是什么？分别起什么作用啊？
> 
> > 查看了代码，感觉代码几乎差不多呀，可能是我没有看懂，恕我冒昧，问的问题可能有点不太专业
> 
> <img alt="联合训练器" width="113" src="https://private-user-images.githubusercontent.com/90132046/336436795-32452256-8994-45e8-b5d0-f59a85496502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDI3MzEsIm5iZiI6MTcxNzUwMjQzMSwicGF0aCI6Ii85MDEzMjA0Ni8zMzY0MzY3OTUtMzI0NTIyNTYtODk5NC00NWU4LWI1ZDAtZjU5YTg1NDk2NTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDEyMDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmN2UwZDg5ZjM5MTBkNTMxNmZhYTM1ODNlZTIzODJmYzFiOGE5MjFlMmY5ZDVmNDY2ZTdkOTNjNTNlMWRkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1mol8IX5muYczLP-6oViLrd4kW0r8viJHn2cwYE9wFo">

这对应论文实验部分table3中的不同策略，federared_ldp是默认使用FedAVG的
![Uploading QQ截图20240604195855.png…]()

**Comment by Sapphire-star** [comment]
> 请问代码联合训练器部分，这个四个训练器的区别是什么？分别起什么作用啊？
> 
> > 查看了代码，感觉代码几乎差不多呀，可能是我没有看懂，恕我冒昧，问的问题可能有点不太专业
> 
> <img alt="联合训练器" width="113" src="https://private-user-images.githubusercontent.com/90132046/336436795-32452256-8994-45e8-b5d0-f59a85496502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDI5MDcsIm5iZiI6MTcxNzUwMjYwNywicGF0aCI6Ii85MDEzMjA0Ni8zMzY0MzY3OTUtMzI0NTIyNTYtODk5NC00NWU4LWI1ZDAtZjU5YTg1NDk2NTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDEyMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGRlYmQwMzczZGRjYzZkOWQ0YmJiMmE2ZWRiMjZkOGVjMTVlZjA3NDA4OTM3MzhlOGQ5YTNlNzcwNDg5MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Aq6BaApdAOaS9mbt6C4Bdt
![table3](https://github.com/Ckano/PFCR/assets/54784881/e53632dd-68bc-42fe-9c16-5f6f2e2c868c)
DZzoys8jtRdXOFAozLkc">

这对应论文实验部分table3中的不同策略，federared_ldp是默认使用FedAVG的

**Comment by Sapphire-star** [comment]
> 请问代码联合训练器部分，这个四个训练器的区别是什么？分别起什么作用啊？
> 
> > 查看了代码，感觉代码几乎差不多呀，可能是我没有看懂，恕我冒昧，问的问题可能有点不太专业
> 
> <img alt="联合训练器" width="113" src="https://private-user-images.githubusercontent.com/90132046/336436795-32452256-8994-45e8-b5d0-f59a85496502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDI5NzYsIm5iZiI6MTcxNzUwMjY3NiwicGF0aCI6Ii85MDEzMjA0Ni8zMzY0MzY3OTUtMzI0NTIyNTYtODk5NC00NWU4LWI1ZDAtZjU5YTg1NDk2NTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDEyMDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NjU3MWM2NDczMTVjMzQ1N2FkMDFjYjMwZTQ2MDkzZDU1OGI0M2MzMDFkMzhhNGVhNGFhZWIwY2Y4MmY1NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7sp9XW8rEO2LnWMPJAgFSPxCj2h8CgLw9kJegSv6f90">
![table3](https://github.com/Ckano/PFCR/assets/54784881/2613eefc-ac02-46f3-a9fd-8010da5cdeeb)

**Comment by lpdbz** [comment]
> 关于四个train训练器的问题，我查看了前面三个fed联合学习训练器代码，除了fed_pretrain.py文件加入了faiss库，其余俩个文件几乎是一样的，请问他们的区别是什么？还有标出来的最后一个文件trainer.py文件的作用是什么呀？
<img width="106" alt="联合学习训练代码" src="https://github.com/Ckano/PFCR/assets/90132046/22ffbb0c-fdf1-4c65-ac00-2865bc14a5f6">

**Comment by Sapphire-star** [comment]
> > 关于四个train训练器的问题，我查看了前面三个fed联合学习训练器代码，除了fed_pretrain.py文件加入了faiss库，其余俩个文件几乎是一样的，请问他们的区别是什么？还有标出来的最后一个文件trainer.py文件的作用是什么呀？
> 
> <img alt="联合学习训练代码" width="106" src="https://private-user-images.githubusercontent.com/90132046/336742772-22ffbb0c-fdf1-4c65-ac00-2865bc14a5f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODQ3NTEsIm5iZiI6MTcxNzU4NDQ1MSwicGF0aCI6Ii85MDEzMjA0Ni8zMzY3NDI3NzItMjJmZmJiMGMtZmRmMS00YzY1LWFjMDAtMjg2NWJjMTRhNWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEwNDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NzNlZTRjMTZmZjc0YmZiZWY3ZTEzZjVmZTc4YzJhNzRkNWMwNDY3NjBiYzI3NjJmMjEyNTRiNzVjMjIxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnAEuAN4H6mYI2gear5xDka26olQlYGVqitbUBYFtwE">

frequency的文件是当初进行实验时的一种尝试，但是实际效果不好，其中有有关统计code出现次数的代码,popcode对应论文的popcode的联邦策略与fedtrainer_popcode配合使用
