### ISSUE TITLE
有关最好测试结果问题

### ISSUE THREAD

**Issue by lpdbz** [Sapphire-star/PFCR#3]
我尝试运行fed_pretrain.py文件，并打印出best_valid_result的结果，目的是还原试验，得到table1相同或相似的结果，但是却打印出None。为了快速得到结果，我缩短了试验时间，即只运行一个epoch，不知道这是否有影响。
> 不知道是不是运行错了代码文件，出现这样的错误，希望可以得到解答，感谢。
<img width="610" alt="最好的验证集结果" src="https://github.com/Ckano/PFCR/assets/90132046/f6beb2f1-9bfe-4ba8-a009-362762701342">
<img width="772" alt="table1" src="https://github.com/Ckano/PFCR/assets/90132046/89ed9867-18b2-4aa0-85c0-f0369446e3c2">

**Comment by Sapphire-star** [comment]
> 我尝试运行fed_pretrain.py文件，并打印出best_valid_result的结果，目的是还原试验，得到table1相同或相似的结果，但是却打印出None。为了快速得到结果，我缩短了试验时间，即只运行一个epoch，不知道这是否有影响。
> 
> > 不知道是不是运行错了代码文件，出现这样的错误，希望可以得到解答，感谢。
> 
> <img alt="最好的验证集结果" width="610" src="https://private-user-images.githubusercontent.com/90132046/336795682-f6beb2f1-9bfe-4ba8-a009-362762701342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODQ1ODIsIm5iZiI6MTcxNzU4NDI4MiwicGF0aCI6Ii85MDEzMjA0Ni8zMzY3OTU2ODItZjZiZWIyZjEtOWJmZS00YmE4LWEwMDktMzYyNzYyNzAxMzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEwNDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzI0MDIzMjNhYjIxMjc5NGE2NWVkMTE2OTUxYzM0ZDBhZTk3YmVjM2Y4MWNmMmZiNWQyMTNkZGU0YzY1YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xg9yk9NIZakVNJ9eCityW5ohbti1icGMaE-Xf_7oIs4"> <img alt="table1" width="772" src="https://private-user-images.githubusercontent.com/90132046/336796674-89ed9867-18b2-4aa0-85c0-f0369446e3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODQ1ODIsIm5iZiI6MTcxNzU4NDI4MiwicGF0aCI6Ii85MDEzMjA0Ni8zMzY3OTY2NzQtODllZDk4NjctMThiMi00YWEwLTg1YzAtZjAzNjk0NDZlM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEwNDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NjczMmNlYTYwMDA3NzI0ZThmZTY4N2FhZWZlOGI1MTcxNjVmZDkzMjVjMmE3ZGI2ODlhN2Q5Nzk2ZWY2YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rY7H2pVREAr2fXMIaUIUUXOo4B_6LDT9gGBdKInPLWQ">

正确的运行方式是先经过fed_train进行联邦预训练，用预训练保存后的参数文件的基础上进行single_train运行知道early stopping停止，最后再使用prompt_finetune文件进行最后的prompt微调，prompt_finetune可以选择用哪种prompt方式

**Comment by lpdbz** [comment]
在single_train文件中导入model下的hgn模块时，并不存在这个模块，请问是什么代码啊  在仓库中没有找到，望告知
<img width="376" alt="hgn模块" src="https://github.com/Ckano/PFCR/assets/90132046/7971d65f-83cc-4b9a-8ee9-3b33c628d881">

**Comment by Sapphire-star** [comment]
> 在single_train文件中导入model下的hgn模块时，并不存在这个模块，请问是什么代码啊 在仓库中没有找到，望告知 <img alt="hgn模块" width="376" src="https://private-user-images.githubusercontent.com/90132046/336841343-7971d65f-83cc-4b9a-8ee9-3b33c628d881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzQ4ODMsIm5iZiI6MTcxNzYzNDU4MywicGF0aCI6Ii85MDEzMjA0Ni8zMzY4NDEzNDMtNzk3MWQ2NWYtODNjYy00YjlhLThlZTktM2IzM2M2MjhkODgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAwNDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODVlNzc3MTBjYzQ2NGQ2YjM2YWMxMWYxODYwYjU2Y2IzMDIyNWYwMzA5NmY2MTI5ZjRmNmYyOTM1NjE1MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FfS01iY__JECo_dUdv6KxLAIkG8ciEH08bH9sY9asQE">

这是我当时跑的baseline，并没有在github里放出，这里可以注释掉

**Comment by lpdbz** [comment]
在运行最后一步的时候，我的运行代码为：python prompt_finetune.py --d=OP --p=save_OP/VQRec-O-10-2024-06-05.pth，想微调OP数据集。但是却报如下错误，faiss加载路径出错，我仔细查看了代码，根据上下文信息，应该是图中的index_path路径的错误，但是我找不到哪里写了默认是OA数据集，正确路径难道不是save_op/OP/....吗？

`
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /root/miniconda3/conda-bld/faiss-pkg_1641228905850/work/faiss/impl/io.cpp:67: Error: 'f' failed: could not open dataset/or-pantry/OA/OA.OPQ32,IVF1,PQ32x8.strict.index for reading: No such file or directory
`

<img width="688" alt="路径错误" src="https://github.com/Ckano/PFCR/assets/90132046/15b75df4-a298-4d27-85d1-3a1ea1c67e64">

**Comment by lpdbz** [comment]
关于最近数据路径的问题，我解决啦，不用回复啦！谢谢
