### ISSUE TITLE
关于损失函数的问题

### ISSUE THREAD

**Issue by Geeker-LStar** [Sapphire-star/PFCR#7]
大佬，当我尝试在 office-art 数据集上跑您的模型的时候（已经改了 yaml 文件中对应的地址），它报错如下：
![image](https://github.com/user-attachments/assets/0e4dd813-1bd8-4f68-8cc5-aca2b168e467)
我看了报错的内容，和损失函数 “CE” 有关，请问是不是在跑 office-art（而不是您写的默认的 or-pantry）的时候需要修改这个损失函数？或者是什么其它的原因？

谢谢大佬！！❤

**Comment by Geeker-LStar** [comment]
谢谢大佬！！

**Comment by Sapphire-star** [comment]
> 大佬，当我尝试在 office-art 数据集上跑您的模型的时候（已经改了 yaml 文件中对应的地址），它报错如下： ![image](https://private-user-images.githubusercontent.com/103357243/350995405-0e4dd813-1bd8-4f68-8cc5-aca2b168e467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTU0NjMsIm5iZiI6MTcyMTY5NTE2MywicGF0aCI6Ii8xMDMzNTcyNDMvMzUwOTk1NDA1LTBlNGRkODEzLTFiZDgtNGY2OC04Y2M1LWFjYTJiMTY4ZTQ2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwMDM5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDg5NWYwZGIzZGUzYzU0MTBkZDI0N2E3MGY1OWYyMjgyMThjZGM2MmI5MDgwYzg5OTdjMmM2OWY1MjA5ZmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tYNxgzZlTFPucvIlQIb2mLtEpfuaKPFeIgJGl_I0lk8) 我看了报错的内容，和损失函数 “CE” 有关，请问是不是在跑 office-art（而不是您写的默认的 or-pantry）的时候需要修改这个损失函数？或者是什么其它的原因？
> 
> 谢谢大佬！！❤

这个错误我没遇到过，但我猜测八成跟你recbole版本有关系，要装我readme里写的版本

**Comment by Geeker-LStar** [comment]
Oooo!! 我更改版本后的确解决了！但是遇到了一个新的问题...
![image](https://github.com/user-attachments/assets/9a128b42-5405-4e69-a4b2-f948b254f9ba)

我已经按照要求修改了 vqrec 和 pretrain 文件，请问上述问题可能的原因是什么呀~？

感谢大佬！

**Comment by Sapphire-star** [comment]
> Oooo!! 我更改版本后的确解决了！但是遇到了一个新的问题... ![image](https://private-user-images.githubusercontent.com/103357243/351162085-9a128b42-5405-4e69-a4b2-f948b254f9ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDEyODMsIm5iZiI6MTcyMTcwMDk4MywicGF0aCI6Ii8xMDMzNTcyNDMvMzUxMTYyMDg1LTlhMTI4YjQyLTU0MDUtNGU2OS1hNGIyLWY5NDhiMjU0ZjliYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwMjE2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmVlMjllZDFhOGNhYjBlMGNiMWNhODIzNjBjNjU0ZTM3YjQ1ZWZkZjdlMzU0NjkyMzRlNjVmMDlmNjUzYzRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IgmM9jyGoEeDuODjFrrFOziOGeP8Ac_Q_ckCEmf3JWU)
> 
> 我已经按照要求修改了 vqrec 和 pretrain 文件，请问上述问题可能的原因是什么呀~？
> 
> 感谢大佬！

可能还是数据集的格式吧，你对着我开放的数据集的格式看一下，fed_pretrain需要两个域的数据

**Comment by Geeker-LStar** [comment]
Emmm 但是我用的就是您提供的 office-arts 数据集诶。。然后数据集格式就是 office-arts 下有三个文件夹：OA，O 和 A。然后 recbole 版本是按照 requirements 中安装的。

**Comment by Sapphire-star** [comment]
> Emmm 但是我用的就是您提供的 office-arts 数据集诶。。然后数据集格式就是 office-arts 下有三个文件夹：OA，O 和 A。然后 recbole 版本是按照 requirements 中安装的。

你这里的office_art下还有个子路径Office,我提供的数据集没有这个子路径，所以是不是你路径设置的问题

**Comment by Geeker-LStar** [comment]
问题已经解决！感谢大佬！！
