### ISSUE TITLE
关于结果的值

### ISSUE THREAD

**Issue by lpdbz** [Sapphire-star/PFCR#8]
您好，我想询问一下，最后训练的prompt_finetune.py函数中结果best valid和test result，您在论文中用的是test result还是best valid结果呢？
<img width="825" alt="Snipaste_2024-10-26_17-42-53" src="https://github.com/user-attachments/assets/18e3f533-96ec-4356-ac88-87e4d0b4cf28">

**Comment by Sapphire-star** [comment]
> 您好，我想询问一下，最后训练的prompt_finetune.py函数中结果best valid和test result，您在论文中用的是test result还是best valid结果呢？ <img alt="Snipaste_2024-10-26_17-42-53" width="825" src="https://private-user-images.githubusercontent.com/90132046/380392259-18e3f533-96ec-4356-ac88-87e4d0b4cf28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjM5MDksIm5iZiI6MTczMDE2MzYwOSwicGF0aCI6Ii85MDEzMjA0Ni8zODAzOTIyNTktMThlM2Y1MzMtOTZlYy00MzU2LWFjODgtODdlNGQwYjRjZjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3M2ViNDVlN2Y4YzU1ZWVmZGIxMzQ1NWEzOGYzMWMyZDU1ZjFiMjdmZWIzOTExYTg2YmNkMDZkYzEwOWE0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9fFjXHt3jXJ2kLmq9bAwOolqCLW67eUaBKGzXe_CpRg">

用的测试集上的结果
