### ISSUE TITLE
Confusion about the reproduction of the original text

### ISSUE THREAD

**Issue by JoyRiderJie** [Sapphire-star/PFCR#9]
Hello, your article is a very interesting one and I am very interested in it, but I still have some questions:

- I couldn’t reproduce the original text when I reproduced this article, but I don’t know what the value of the `index_pretrain_dataset` field is in the four files under the [props](https://github.com/Sapphire-star/PFCR/tree/main/props) folder in the code, because the fields in several files do not match.

Below is my configuration
![71afa265ba7ae96a587458e39485146](https://github.com/user-attachments/assets/9f14d061-31f5-4500-9e05-41c0b4d68354)

![342e641a122963880cba26f66c78a96](https://github.com/user-attachments/assets/a160e28d-a297-462a-a1a5-08dc2f8d70c6)

I would like to thank the author again and hope to get your reply！

**Comment by Sapphire-star** [comment]
> Hello, your article is a very interesting one and I am very interested in it, but I still have some questions:
> 
> * I couldn’t reproduce the original text when I reproduced this article, but I don’t know what the value of the `index_pretrain_dataset` field is in the four files under the [props](https://github.com/Sapphire-star/PFCR/tree/main/props) folder in the code, because the fields in several files do not match.
> 
> Below is my configuration ![71afa265ba7ae96a587458e39485146](https://private-user-images.githubusercontent.com/100121431/387707186-9f14d061-31f5-4500-9e05-41c0b4d68354.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDY5MzEsIm5iZiI6MTczNDI0NjYzMSwicGF0aCI6Ii8xMDAxMjE0MzEvMzg3NzA3MTg2LTlmMTRkMDYxLTMxZjUtNDUwMC05ZTA1LTQxYzBiNGQ2ODM1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwNzEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzk1YjY1MTkyM2YzMzhkZWExNzdkYjVmNjZiMDY4ODM4MWFkOWFkMmEzNjg4MTk0ZTYxZDNlMDc3YmIyNTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.byDBmJX7KpS8ho2gbkdVqzo1L4Ig1I52TNMkvu9AmGc)
> 
> ![342e641a122963880cba26f66c78a96](https://private-user-images.githubusercontent.com/100121431/387707356-a160e28d-a297-462a-a1a5-08dc2f8d70c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDY5MzEsIm5iZiI6MTczNDI0NjYzMSwicGF0aCI6Ii8xMDAxMjE0MzEvMzg3NzA3MzU2LWExNjBlMjhkLWEyOTctNDYyYS1hMWE1LTA4ZGMyZjhkNzBjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwNzEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2JiM2EzN2I5NDcwMjNhODU3NjUwOTgxNDQ2NDY4ZGFiOWFkYTM5YzkzZWRhMWVjNmMzNWY3MjFkZDNmZDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.egS8CxB8p3LXoFggVSsrYexv--3rUYR-2EMnmq_p0qM)
> 
> I would like to thank the author again and hope to get your reply！

Hello, the parameter settings you mentioned are all abbreviations of the first letter of the dataset. For example, for the "office arts" dataset, if you set O in the YAML file, the model will correspondingly find the relevant Office files

**Comment by Sapphire-star** [comment]
#10 I have also written a detailed explanation here

**Comment by JoyRiderJie** [comment]
> > Hello, your article is a very interesting one and I am very interested in it, but I still have some questions:
> > 
> > * I couldn’t reproduce the original text when I reproduced this article, but I don’t know what the value of the `index_pretrain_dataset` field is in the four files under the [props](https://github.com/Sapphire-star/PFCR/tree/main/props) folder in the code, because the fields in several files do not match.
> > 
> > Below is my configuration ![71afa265ba7ae96a587458e39485146](https://private-user-images.githubusercontent.com/100121431/387707186-9f14d061-31f5-4500-9e05-41c0b4d68354.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDY5MzEsIm5iZiI6MTczNDI0NjYzMSwicGF0aCI6Ii8xMDAxMjE0MzEvMzg3NzA3MTg2LTlmMTRkMDYxLTMxZjUtNDUwMC05ZTA1LTQxYzBiNGQ2ODM1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwNzEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzk1YjY1MTkyM2YzMzhkZWExNzdkYjVmNjZiMDY4ODM4MWFkOWFkMmEzNjg4MTk0ZTYxZDNlMDc3YmIyNTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.byDBmJX7KpS8ho2gbkdVqzo1L4Ig1I52TNMkvu9AmGc)
> > ![342e641a122963880cba26f66c78a96](https://private-user-images.githubusercontent.com/100121431/387707356-a160e28d-a297-462a-a1a5-08dc2f8d70c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDY5MzEsIm5iZiI6MTczNDI0NjYzMSwicGF0aCI6Ii8xMDAxMjE0MzEvMzg3NzA3MzU2LWExNjBlMjhkLWEyOTctNDYyYS1hMWE1LTA4ZGMyZjhkNzBjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwNzEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2JiM2EzN2I5NDcwMjNhODU3NjUwOTgxNDQ2NDY4ZGFiOWFkYTM5YzkzZWRhMWVjNmMzNWY3MjFkZDNmZDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.egS8CxB8p3LXoFggVSsrYexv--3rUYR-2EMnmq_p0qM)
> > I would like to thank the author again and hope to get your reply！
> 
> Hello, the parameter settings you mentioned are all abbreviations of the first letter of the dataset. For example, for the "office arts" dataset, if you set O in the YAML file, the model will correspondingly find the relevant Office files

Okay, thank you very much!
